'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace DAL.TimeCore

    Partial Public Class DepartmentUser
        Inherits DevExpress.Persistent.BaseImpl.BaseObject
        Dim _User As User
        <Association("DepartmentUserReferencesUser")>
        Public Property User() As User
            Get
                Return _User
            End Get
            Set(ByVal value As User)
                SetPropertyValue(Of User)(NameOf(User), _User, value)
            End Set
        End Property
        Dim _Department As Department
        <Association("DepartmentUserReferencesDepartement")>
        Public Property Department() As Department
            Get
                Return _Department
            End Get
            Set(ByVal value As Department)
                SetPropertyValue(Of Department)(NameOf(Department), _Department, value)
            End Set
        End Property
        Dim _StartDate As DateTime
        Public Property StartDate() As DateTime
            Get
                Return _StartDate
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(StartDate), _StartDate, value)
            End Set
        End Property
        Dim _EndDate As DateTime
        Public Property EndDate() As DateTime
            Get
                Return _EndDate
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(EndDate), _EndDate, value)
            End Set
        End Property
    End Class

End Namespace
