'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace DAL.TimeCore

    Partial Public Class TimeTableDetail
        Inherits DevExpress.Persistent.BaseImpl.BaseObject
        Dim _TimeTable As TimeTable
        <Association("TimeTableDetailTimeSlotReferencesTimeTable")>
        Public Property TimeTable() As TimeTable
            Get
                Return _TimeTable
            End Get
            Set(ByVal value As TimeTable)
                SetPropertyValue(Of TimeTable)(NameOf(TimeTable), _TimeTable, value)
            End Set
        End Property
        Dim _DayNum As Integer
        Public Property DayNum() As Integer
            Get
                Return _DayNum
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(DayNum), _DayNum, value)
            End Set
        End Property
        Dim _TimeSlot As WorkTimeSlot
        <Association("TimeTableDetailTimeSlotReferencesTimeSlot")>
        Public Property TimeSlot() As WorkTimeSlot
            Get
                Return _TimeSlot
            End Get
            Set(ByVal value As WorkTimeSlot)
                SetPropertyValue(Of WorkTimeSlot)(NameOf(TimeSlot), _TimeSlot, value)
            End Set
        End Property
        Dim _TimeSlotNum As Integer
        Public Property TimeSlotNum() As Integer
            Get
                Return _TimeSlotNum
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(TimeSlotNum), _TimeSlotNum, value)
            End Set
        End Property
    End Class

End Namespace
