'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace DAL.TimeCore

    Partial Public Class TimeTableAffectation
        Inherits DevExpress.Persistent.BaseImpl.BaseObject
        Dim _User As User
        <Association("TimeTableAffectationReferencesUser")>
        Public Property User() As User
            Get
                Return _User
            End Get
            Set(ByVal value As User)
                SetPropertyValue(Of User)(NameOf(User), _User, value)
            End Set
        End Property
        Dim _TimeTable As TimeTable
        <Association("UserTimeTableReferencesTimeTable")>
        Public Property TimeTable() As TimeTable
            Get
                Return _TimeTable
            End Get
            Set(ByVal value As TimeTable)
                SetPropertyValue(Of TimeTable)(NameOf(TimeTable), _TimeTable, value)
            End Set
        End Property
        Dim _StartDay As DateTime
        Public Property StartDay() As DateTime
            Get
                Return _StartDay
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(StartDay), _StartDay, value)
            End Set
        End Property
        Dim _EndDay As DateTime
        Public Property EndDay() As DateTime
            Get
                Return _EndDay
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(EndDay), _EndDay, value)
            End Set
        End Property
    End Class

End Namespace
