'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace DAL.TimeCore

    Partial Public Class TimeTable
        Inherits DevExpress.Persistent.BaseImpl.BaseObject
        Dim _Code As String
        Public Property Code() As String
            Get
                Return _Code
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Code), _Code, value)
            End Set
        End Property
        Dim _Name As String
        Public Property Name() As String
            Get
                Return _Name
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Name), _Name, value)
            End Set
        End Property
        Dim _Kind As DAL.TimeCore.TimeTableKind
        Public Property Kind() As DAL.TimeCore.TimeTableKind
            Get
                Return _Kind
            End Get
            Set(ByVal value As DAL.TimeCore.TimeTableKind)
                SetPropertyValue(Of DAL.TimeCore.TimeTableKind)(NameOf(Kind), _Kind, value)
            End Set
        End Property
        Dim _Frequency As Integer
        Public Property Frequency() As Integer
            Get
                Return _Frequency
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(Frequency), _Frequency, value)
            End Set
        End Property
        Dim _FirstDayOfWeek As System.DayOfWeek
        Public Property FirstDayOfWeek() As System.DayOfWeek
            Get
                Return _FirstDayOfWeek
            End Get
            Set(ByVal value As System.DayOfWeek)
                SetPropertyValue(Of System.DayOfWeek)(NameOf(FirstDayOfWeek), _FirstDayOfWeek, value)
            End Set
        End Property
        <Association("TimeTableDetailTimeSlotReferencesTimeTable"), Aggregated()>
        Public ReadOnly Property TimeTableDetails() As XPCollection(Of TimeTableDetail)
            Get
                Return GetCollection(Of TimeTableDetail)(NameOf(TimeTableDetails))
            End Get
        End Property
        <Association("UserTimeTableReferencesTimeTable"), Aggregated()>
        Public ReadOnly Property UserTimeTables() As XPCollection(Of TimeTableAffectation)
            Get
                Return GetCollection(Of TimeTableAffectation)(NameOf(UserTimeTables))
            End Get
        End Property
    End Class

End Namespace
