'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace DAL.TimeCore

    Partial Public Class User
        Inherits DevExpress.Persistent.BaseImpl.BaseObject
        Dim _Code As String
        Public Property Code() As String
            Get
                Return _Code
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Code), _Code, value)
            End Set
        End Property
        <Association("TimeTableAffectationReferencesUser"), Aggregated()>
        Public ReadOnly Property TimeTableAffectations() As XPCollection(Of TimeTableAffectation)
            Get
                Return GetCollection(Of TimeTableAffectation)(NameOf(TimeTableAffectations))
            End Get
        End Property
        <Association("DepartmentUserReferencesUser"), Aggregated()>
        Public ReadOnly Property DepartmentUsers() As XPCollection(Of DepartmentUser)
            Get
                Return GetCollection(Of DepartmentUser)(NameOf(DepartmentUsers))
            End Get
        End Property
    End Class

End Namespace
