'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace DAL.TimeCore

    Partial Public Class WorkBreak
        Inherits XPObject
        Dim _Code As String
        Public Property Code() As String
            Get
                Return _Code
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Code), _Code, value)
            End Set
        End Property
        Dim _WorkTimeSlot As WorkTimeSlot
        Public Property WorkTimeSlot() As WorkTimeSlot
            Get
                Return _WorkTimeSlot
            End Get
            Set(ByVal value As WorkTimeSlot)
                SetPropertyValue(Of WorkTimeSlot)(NameOf(WorkTimeSlot), _WorkTimeSlot, value)
            End Set
        End Property
        Dim _TimeStart As TimeSpan
        Public Property TimeStart() As TimeSpan
            Get
                Return _TimeStart
            End Get
            Set(ByVal value As TimeSpan)
                SetPropertyValue(Of TimeSpan)(NameOf(TimeStart), _TimeStart, value)
            End Set
        End Property
        Dim _TimeEnd As TimeSpan
        Public Property TimeEnd() As TimeSpan
            Get
                Return _TimeEnd
            End Get
            Set(ByVal value As TimeSpan)
                SetPropertyValue(Of TimeSpan)(NameOf(TimeEnd), _TimeEnd, value)
            End Set
        End Property
    End Class

End Namespace
